### ISSUE TITLE
01 - Display important details of a single entry

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#1]
# Value Proposition

**As a** user
**I need** to see an flea market/shop
**to be able to** get the information about the flea market/shop I am interested in.

# Description

Scribble / design or text
<img width="363" alt="Single entry" src="https://user-images.githubusercontent.com/98806457/167385471-1c227309-6df7-40b9-a5a6-b577fe9df5ab.png">

# Acceptance Criteria

- [x] The entry's category is displayed
- [x] The flea market's/shop's name is displayed
- [x] The flea market's/shop's  location is displayed

# Tasks

- [x] Create the data structure to hold the entry details
- [x] Create a new component to render the data in a `<h2>` and `<p>` tag
- [x] The component receives entry details via props
- [x] Add component to the app
- [x] Add styled-components
- [x] Add to Storybook
- [x] Add test to check if data is rendered
- [x] Check accessibility
- [x] Deploy for usability and UX testing 
- [x] Check on mobile phone

# Complexity
M
