### ISSUE TITLE
07 - Edit an entry

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#12]
# Value Proposition

**As a** user
**I need** to have an edit function 
**to be able to** keep the list of flea markets/shops up to date.

# Description

![Edit entry](https://user-images.githubusercontent.com/98806457/169299267-290e6e6a-7c83-4a22-a033-aa62542c0ad5.png)

# Acceptance Criteria

- [x] A button to edit the entry is displayed on the unfolded card, labeled "Ändern"
- [x] When the button is clicked, the entry can be edited and the button toggels, labeled "Speichern"
- [x] After clicking the save button changes are updated

# Tasks

- [x] Create a button component
- [x] Add an onClick event to the button to edit an entry
- [x] Add styled-components
- [x] Add to Storybook
- [x] Write test to check if the button is there
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
L
