### ISSUE TITLE
08 - Split pages and add footer with navbar

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#13]
# Value Proposition

**As a** user
**I need** to have seperate pages and a footer with clickable icons
**to be able to** have a better overview in the app.

# Description

![Image](https://user-images.githubusercontent.com/98806457/169797619-08ad7c88-365b-47c2-9370-d3b7229b59cf.png)

# Acceptance Criteria

- [x] The form and the entries are on seperate pages
- [x] Inside the footer is a navbar with two icons (home and new entry)
- [x] When you click on one icon, you are directed to the connected page and the color of the icon changes

# Tasks

- [x] Split the existing page in two pages
- [x] Add a footer component
- [x] Add the two icons and link them to the associated page (navbar)
- [x] Add component to the app
- [x] Add styled-components
- [x] Add to Storybook
- [x] Write test
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
M

**Comment by F-Kirchhoff** [comment]
Very nice! I would only suggest the following: 
- the footer with clickable icons normally is called a navigation or navbar
- the steps 'add component to the app' and 'add styled components' are quite detailed and so common that you don't really need to mention them.
Besides that it looks very promising ✨

**Comment by NadineGrosskreuz** [comment]
Thanks for your feedback, I adjusted it! :)
