### ISSUE TITLE
09 - Bookmark an entry

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#14]
# Value Proposition

**As a** user
**I need** to have a bookmark function
**to be able to** to add the flea markets/shops I like to a seperate page.

# Description

![Bookmark entry](https://user-images.githubusercontent.com/98806457/169829795-1f3cb2c7-6a43-4db8-bf47-d5aa0a0b2573.png)

# Acceptance Criteria

- [x] Each entry on the list will show a button (a heart) to mark the entry 
- [x] When clicking on the button the respective entry is added to the bookmark page and the heart is filled
- [x] When clicking on the button again the entry is removed from the bookmark page and the heart is not filled
- [x] The navigation shows a button for the bookmark page
- [x] All bookmarked entries are shown on the bookmark page

# Tasks

- [x] Create a button component
- [x] Create the bookmark page
- [x] Add a heart icon to the footer and link it to the bookmark page
- [x] Add an onClick event to the button to add and remove the entry from the bookmark page
- [x] Add styled-components
- [x] Write test
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
M
