### ISSUE TITLE
13 - Rework form and modals

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#17]
# Value Proposition

**As a** user
**I need** to have a well functioning form and more information about my actions
**to be able to** have a good user experience.

# Description

Adding an entry must be possible again and there shall be more modals.
# Acceptance Criteria

- [x] The products category should no longer be there
- [x] After editing an entry there should be a message "Änderungen wurden gespeichert"
- [x] After deleting an entry there should be a message "Dein Eintrag wurde gelöscht"
- [x] After the entry is created, the user is directed to the home page
- [x] The "Weitere Informationen" field should be larger than the other input fields
- [x] The input fields cannot be sent with only blank characters

# Tasks

- [x] Remove the products category
- [x] Add a hidden input field for positions
- [x] Add a modal "Deine Änderungen wurden gespeichert" after an entry was revised
- [x] Add a modal "Dein Eintrag wurde gelöscht" after an entry was deleted
- [x] Add push/router to the onSubmit function 
- [x] Change the field "Weitere Informationen" from input to textarea
- [x] Add "pattern: /\S(.*\S)?/" to the input fields

# Complexity
L

**Comment by Luxa23** [comment]
Hi @NadineGrosskreuz, the story looks good to me. You could specify the testing task a bit more since it is not as on point as the others.

**Comment by NadineGrosskreuz** [comment]
Thanks for your feedback, I will think about it!
