### ISSUE TITLE
04 - See details of an entry

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#2]
# Value Proposition

**As a** user
**I need** to have detailed information about the entry when clicking on the button
**to be able to** have a better overview of the entries in the list.

# Description

![Details entry](https://user-images.githubusercontent.com/98806457/168598370-b7dd6673-df19-4f3f-b9fa-51592bbf7122.png)

# Acceptance Criteria

- [x] When closed, only the category, name and address are displayed
- [x] By clicking on the button the missing information is shown (products, additional information, already visited, rating)
- [x] By clicking on the button on an expanded entry the entry collapses again

# Tasks

- [x] Add the missing information in the array of multiple entries (see #3)
- [x] Add them in the props and functions
- [x] Create the accordion button 
- [x] Add styled-components
- [x] Add to Storybook
- [x] Update test to check if data and button are rendered
- [x] Add test to check if button functionality works
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
M

**Comment by irenepapaspyratos** [comment]
You could specify, which informations should be shown - at least in tasks or even in both sections. Besides that, assuming your developer-team creates new branches by themselves, I think it's fine to go.
