### ISSUE TITLE
10 - Display a map

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#22]
# Value Proposition

**As a** user
**I need** a map
**to be able to** to see where the flea markets and shops are located.

# Description

![Image](https://user-images.githubusercontent.com/98806457/170878189-6559b5db-98f5-4b83-98a0-961a13efb923.png)

# Acceptance Criteria

- [x] There is an extra page where the map is displayed
- [x] The page is linked in the footer with a map icon
- [x] The map can be zoomed and moved
- [x] When the map is rendered, it shows the current location of the user
- [x] The user is asked if location-data is permitted to be shared
- [x] The map should be centered in the middle of Germany, if the location of the user is not available/shared

# Tasks

- [x] Create the map page
- [x] Add a map icon to the footer and link it to the map page
- [x] Create a map component to render the map using Leaflet
- [x] Create the function LocationMarker
- [x] Add component to map page
- [x] Add to Storybook
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
M

**Comment by oy-gen** [comment]
- [x]  lgtm

**Comment by NadineGrosskreuz** [comment]
Thanks! :)
