### ISSUE TITLE
11 - Show entries on map

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#24]
# Value Proposition

**As a** user
**I need** to see my entries on the map
**to be able to** see where the flea markets and shops are located.

# Description

![Image](https://user-images.githubusercontent.com/98806457/170890491-90cf5a04-9f9f-466b-88bb-4d82b1177d9a.png)

# Acceptance Criteria

- [x] On the map there are markers for each entry
- [x] When clicking on a marker a popup with the name and the category is shown
- [x] The popup can be closed by clicking on a "x" in the top right corner

# Tasks

- [x] Create a component for the entry markers
- [x] Inside the marker implement a popup that renders the respective name when clicking on the marker
- [x] Implement the marker inside the map component
- [x] Use an API to convert the addresses into longitude and latitude
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
M
