### ISSUE TITLE
Adaptations for better accessibility

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#26]
# Value Proposition

**As a** user
**I need** to have an accessible application
**to be able to** use the application with a disability without problems.

# Description

Adjustments in the code.

# Acceptance Criteria

- [ ] The application can easily be used with a screen reader

# Tasks

- [ ] Add a title element
- [ ] Add a h1 on each page (the name of the app in the head)

# Complexity
XS
