### ISSUE TITLE
Adjust styling

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#27]
# Value Proposition

**As a** user
**I need** a nicely designed application
**to be able to** have a good experience while using it.

# Description

Scribble / design or text

# Acceptance Criteria

- [ ] The form has a nice styling
- [ ] The application looks good on desktop and mobile (especially in the measurements 375x667px, iPhone SE or 6/7/8)

# Tasks

- [ ] Put colors in GlobalStyles

# Complexity
M
