### ISSUE TITLE
12 - Add searchbar

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#29]
# Value Proposition

**As a** user
**I need** a way to search for specific entries
**to be able to** find what I want more quickly.

# Description

![Image](https://user-images.githubusercontent.com/98806457/171827419-c429196b-997f-4cf4-99e1-6c7f335904ed.png)

# Acceptance Criteria

- [x] The searchbar with a "Suchen" button is displayed at the top of the home page
- [x] After clicking the button the entries that match are displayed
- [x] If the searchbar is emptied all entries are shown

# Tasks

- [x] Create a search bar 
- [x] Create a function in CardList
- [x] Add component with props to index page
- [x] Add styled-components
- [x] Add to Storybook
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
L

**Comment by F-Kirchhoff** [comment]
Hey Nadine, your userstory is a bit contradictory, at one point the entries get updated when a user types into the search bar, in another part you want to add an eventListener on a Click of the user. If you want to adapt the click version, you should state that the magnifier icon is wrapped in a button. Also, I have a suggestion for the acceptance criteria: What should happen if the search bar gets emtied? Are then all entries displayed again?
In general, the value discription does not contain a specific solution for the needs of the user, like a searchbar in your case. It would normally state what the user need is, not what the solution to that need is. You could restate the description as: `As a user, I need a way to search for specific entries in order to find what I want more quickly.`
Besides these two points your userstory is top notch!

**Comment by F-Kirchhoff** [comment]
btw: the idea behind the value description is that it normally is stated before the dev team has found the optimal solution to the need of the user. By stating it this way you stay open for other possible ways to solve this need, like a list of tags for example, a date picker etc.
