### ISSUE TITLE
03 - List entries

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#3]
# Value Proposition

**As a** user
**I need** to see a list of flea markets and shops
**to be able to** to get a better overview of all the flea markets and shops.

# Description

<img width="360" alt="List of entries" src="https://user-images.githubusercontent.com/98806457/167387172-062f780e-a651-4516-bab5-5dfce3d07fd9.png">

# Acceptance Criteria

- [x] Each entry should be visually separated
- [x] Each entry should be displayed with the important details (see #1)
- [x] All entries should be displayed

# Tasks

- [x] Create a data structure to hold an array of multiple entries
- [x] Create a component to render the list of entries
- [x] The component receives the array via props
- [x] The list component contains the card component defined in #1 
- [x] Remove single card from the app and add the list component instead
- [x] Add styled-components
- [x] Add to Storybook
- [x] Add a test to check if all given entries are rendered
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
S

**Comment by cintiavazquez** [comment]
Hi Nadine, great second user story!
I can't see anything wrong with it, but I'd maybe be more specific in the tasks after "The component receives the array via props".  I'd add that you then map over the array to display all cards (and check that your static data has IDs to act as keys).

**Comment by NadineGrosskreuz** [comment]
Thank you, I adjusted it!
