### ISSUE TITLE
14 - Add header with logo

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#32]
# Value Proposition

**As a** user
**I need** to see where I am in the app
**to be able to** have a good user experience.

# Description

![Image](https://user-images.githubusercontent.com/98806457/172065530-fd1828fc-1faa-4665-983c-4648ff6276c7.png)

# Acceptance Criteria

- [x] The header consists of a logo on the left and the name of the respective page: "Home", "Eintrag erstellen", "Favoriten", "Karte" in the middle
- [x] The header is visible on all pages at the same position

# Tasks

- [x] Create a header 
- [x] Add the logo to the header
- [x] Add the header to the different pages
- [x] Add styled-components
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
S
