### ISSUE TITLE
16 - Clean and fix code

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#33]
# Value Proposition

**As a** developer
**I need** to have a clean and working code
**to be able to** get along well with my code.

# Description

Everything works as it should.
Another person understands the code quickly and finds his way around easily.

# Acceptance Criteria

- [x] The code is clean and well structured
- [x] There are no unnecessary styling features
- [x] The styled-components are well structured
- [x] All tests work
- [x] When entries are changed, the map continues to function
- [x] The bookmark button is always in the same place

# Tasks

- [x] Restructuring the styled-components with variants (e.g. Button.styled.js)
- [x] Remove unnecessary styling features
- [x] Change Footer.spec and remove CardList.spec
- [x] Rewrite if(entryToUpdate) of the submit function
- [x] Use only position top and right for the placement of the icon
- [x] Add a title element to each page
- [x] Add more static data and remove services folder

# Complexity
M
