### ISSUE TITLE
05 - Create an entry

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#4]
# Value Proposition

**As a** user
**I need** to add a new entry to my list
**to be able to** add my own flea markets and shops to the list.

# Description

![Create entry](https://user-images.githubusercontent.com/98806457/168599224-72edad42-853d-4cff-9a13-571375c32bc3.png)

# Acceptance Criteria

- [x] The name field is mandatory. There is an error message if no value is entered.
- [x] An input field for the name is displayed, labeled "Name", text, max. 50 characters
- [x] An input field for the address is displayed, labeled "Adresse", text, max. 150 characters
- [x] Radio buttons for the categories of products are displayed, labeled "Kleidung", "Deko", "Haushaltswaren", "Medien", "Antiquitäten", "Spielsachen"
- [x] An input field for more information is displayed, labeled "Weitere Infos", text, max. 300 characters
- [x] Radio buttons  are displayed, labeled "Ich war schon da", "Ich war noch nicht da", in front "Schon besucht?"
- [x] Radio buttons  are displayed, labeled "Mag ich!, "Nicht mein Fall!, in front "Bewertung"
- [x] A button to save the entry is displayed, labeled "Eintrag hinzufügen"
- [x] After saving the new entry will appear in the list of all products (see #3 )
- [x] After saving there is a pop up with a confirmation message "Eintrag wurde hinzugefügt"
- [x] After saving the input fields are cleared

# Tasks

- [x] Create a form component with React Hook Form
- [x] Create radio buttons
- [x] Create button component
- [x] Create input component
- [x] Add form fields with their labels
- [x] Mark "Name" field as required
- [x] Add text length validation (for fields "Name", "Adresse" and "Weitere Infos"
- [x] Add the entry to the list of existing entries in the data structure after submitting the form with valid data
- [x] Install nanoid
- [x] Add form component to app
- [x] Add styled-components
- [x] Add to Storybook: Input, Button, Form
- [x] Write tests to check if all required elements are in the form
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
XL

**Comment by UrsulaMontag** [comment]
Sehr gute userstory, Nadine! 🤩
