### ISSUE TITLE
06 - Delete an entry

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#5]
# Value Proposition

**As a** user
**I need** to delete an entry
**to be able to** keep the list of flea markets and secondhand stores up to date.

# Description

![Delete entry](https://user-images.githubusercontent.com/98806457/168783667-856d2ba0-a211-43a7-b914-752f7e5215e6.png)

# Acceptance Criteria

- [x] A button to delete the entry is displayed on the unfolded card, labeled "Löschen"
- [x] After clicking the button the entry disappears and is not in the list anymore

# Tasks

- [x] Create a button component
- [x] Add an onClick event to the button to delete an entry
- [x] Add zustand for cleaner code
- [x] Add styled-components
- [x] Add to Storybook
- [x] Write test to check if the button is there
- [x] Check accessibility
- [x] Deploy for usability and UX testing
- [x] Check on mobile phone

# Complexity
M

**Comment by irenepapaspyratos** [comment]
Add an onClick event to the button... Means, an event is fired... but what shall this firing initiate?  😉
