### ISSUE TITLE
02 - Implement a Typography component

### ISSUE THREAD

**Issue by NadineGrosskreuz** [NadineGrosskreuz/capstone-project#8]

**Comment by NadineGrosskreuz** [comment]
**As a** developer
**I need** a Typography component
**to be able to** organize different typo styles in a reusable way.

# Description

For having clear and reusable typography elements in my app, I need the Typography component that renders the respective styling.

# Acceptance Criteria

- [ ] All typos are reusable

# Tasks

- [ ] Create a Typography component inside the UI folder
- [ ] Write the Typography function including the already existing typo-elements
- [ ] Change the existing typo styled components 

# Complexity
S
